apiVersion: apps/v1
kind: Deployment
metadata:
    name: headscale
spec:
    replicas: 1
    selector:
        matchLabels:
            app: headscale
    template:
        metadata:
            labels:
                app: headscale
        spec:
            securityContext:
                fsGroup: 1000
                runAsUser: 1000
            containers:
                - name: headscale
                  image: headscale/headscale:latest
                  args: ["serve", "-c", "/etc/headscale/config.yaml"]
                  env:
                      - name: HEADSCALE_UNIX_SOCKET
                        value: /var/lib/headscale/headscale.sock
                  ports:
                      - containerPort: 8080
                  volumeMounts:
                      - name: config-volume
                        mountPath: /etc/headscale/config.yaml
                        subPath: config.yaml
                      - name: data
                        mountPath: /var/lib/headscale
            volumes:
                - name: config-volume
                  configMap:
                      name: headscale-config
                - name: data
                  persistentVolumeClaim:
                      claimName: headscale-pvc
